### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'map' in version 2.7.0

### ISSUE THREAD

**Issue by Stiksels** [morph-kgc/morph-kgc#229]
####  What Happens?
When I update my morph_kgc version from 2.6.4 to 2.7.0, without modifying my code, I now get an AttributeError

#### To Reproduce

```
config_ini = f"""[CONFIGURATION]
                output_format=N-QUADS

                [DataSource1]
                mappings=/tmp/{data_type}_rml.ttl
                """
```

```
Traceback (most recent call last):
  File "/workspace/demo-dataproduct-9f1ad6510aa76f5a/transformer/main.py", line 73, in <module>
    push_data(LOCATIE_TYPE, QUERY_LATEST_LOCATIE_DATE)
  File "/workspace/demo-dataproduct-9f1ad6510aa76f5a/transformer/main.py", line 59, in push_data
    graph_store = generate_rdf_graph(config_ini)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/demo-dataproduct-9f1ad6510aa76f5a/transformer/rdf_utils.py", line 37, in generate_rdf_graph
    g = morph_kgc.materialize_oxigraph(config_ini_path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/micromamba/envs/dataproduct/lib/python3.11/site-packages/morph_kgc/__init__.py", line 76, in materialize_oxigraph
    triples = materialize_set(config, python_source)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/micromamba/envs/dataproduct/lib/python3.11/site-packages/morph_kgc/__init__.py", line 39, in materialize_set
    rml_df, fnml_df = retrieve_mappings(config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/micromamba/envs/dataproduct/lib/python3.11/site-packages/morph_kgc/mapping/mapping_parser.py", line 21, in retrieve_mappings
    rml_df, fnml_df = mappings_parser.parse_mappings()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/micromamba/envs/dataproduct/lib/python3.11/site-packages/morph_kgc/mapping/mapping_parser.py", line 476, in parse_mappings
    self._get_from_r2_rml()
  File "/home/gitpod/micromamba/envs/dataproduct/lib/python3.11/site-packages/morph_kgc/mapping/mapping_parser.py", line 507, in _get_from_r2_rml
    data_source_rml_df, data_source_fnml_df = self._parse_data_source_mapping_files(section_name)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/micromamba/envs/dataproduct/lib/python3.11/site-packages/morph_kgc/mapping/mapping_parser.py", line 567, in _parse_data_source_mapping_files
    return _transform_mappings_into_dataframe(mapping_graph, section_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/micromamba/envs/dataproduct/lib/python3.11/site-packages/morph_kgc/mapping/mapping_parser.py", line 390, in _transform_mappings_into_dataframe
    fnml_df = fnml_df.map(str)
              ^^^^^^^^^^^
  File "/home/gitpod/micromamba/envs/dataproduct/lib/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'map'. Did you mean: 'max'?
```
#### Environment (please complete the following information):
 - OS: Linux gitpod workspace:latest
 - Python version: [e.g. 3.11.8]
 - Morph-KGC version: 2.7.0

**Comment by arenas-guerrero-julian** [comment]
Hi @Stiksels 

It looks like it is failing in the pandas `map` method when processing RML-FNML.

RML-FNML test cases are passing, I would need some more information. Could you please do a `pip list` and provide the output?

Could you also attach an example of data and mappings to reproduce the error?

**Comment by Stiksels** [comment]
Hi @arenas-guerrero-julian , thanks for your fast reply.

By pointing me to the pandas library, I checked the current version (2.0.0) and bumped it to 2.2.1. This did the trick; I am now able to generate named graphs with morph-kgc, using yarrrml instead of rml.

Thanks for the support!
