### ISSUE TITLE
AttributeError: module 'falcon' has no attribute '__version__'

### ISSUE THREAD

**Issue by aharth** [morph-kgc/morph-kgc#308]
#### Environment (please complete the following information):
 - OS: Debian trixie
 - Python version: Python 3.13.2

#### Morph-KGC Version
Please provide the version of Morph-KGC you are trying to install.

The one that is currently available via pip.

#### Installation Method
Please specify how you tried to install Morph-KGC from a clean environment (e.g. PyPi, from source).

```
$ python3 -m venv .
...
$ ./bin/pip install morph-kgc
```
#### Installation Logs
If possible, please copy and paste the installation logs when attempting to install Morph-KGC.
```
Collecting morph-kgc
  Using cached morph_kgc-2.8.1-py3-none-any.whl.metadata (11 kB)
Collecting duckdb<2.0.0,>=0.10.0 (from morph-kgc)
  Using cached duckdb-1.2.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (966 bytes)
Collecting elementpath<5.0.0,>=4.0.0 (from morph-kgc)
  Using cached elementpath-4.7.0-py3-none-any.whl.metadata (7.0 kB)
Collecting falcon<4.0.0,>=3.0.0 (from morph-kgc)
  Using cached falcon-3.1.3.tar.gz (577 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/config/expand.py", line 71, in __getattr__
          return next(
              ast.literal_eval(value)
              for target, value in self._find_assignments()
              if isinstance(target, ast.Name) and target.id == attr
          )
      StopIteration
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/config/expand.py", line 185, in read_attr
          value = getattr(StaticModule(module_name, spec), attr_name)
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/config/expand.py", line 77, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: falcon has no attribute __version__
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/tmp/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 197, in <module>
        File "<string>", line 174, in run_setup
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 160, in setup
          dist.parse_config_files()
          ~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 648, in parse_config_files
          setupcfg.parse_configuration(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
              self, self.command_options, ignore_option_errors=ignore_option_errors
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 188, in parse_configuration
          meta.parse()
          ~~~~~~~~~~^^
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 502, in parse
          section_parser_method(section_options)
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 477, in parse_section
          self[name] = value
          ~~~~^^^^^^
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 294, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 600, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 419, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
                 ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-284_ruxr/overlay/lib/python3.13/site-packages/setuptools/config/expand.py", line 191, in read_attr
          return getattr(module, attr_name)
      AttributeError: module 'falcon' has no attribute '__version__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by arenas-guerrero-julian** [comment]
Hi @aharth,

I have checked that morph-kgc works with Python 3.13 and upgraded Falcon to its latest version. Could you try installing from source?:

```bash
pip install git+https://github.com/morph-kgc/morph-kgc.git
```

**Comment by aharth** [comment]
Yes, that works, thanks!
